[global]
deviation = 20
weight = 40
size = 15.0
width = 1000
height = 600

[colors]
cyan = [0, 255, 255]
orange = "#AA7700"
grey = [150, 150, 150]
red = "#FF0000"
redcpy = "red"

[themes]
rust = [["cyan", 10], ["orange", 60], ["grey", 20]]
crimson = [["red", 50], ["grey", 10]]

[shapes]
all = []

[data.patterns]
nb_f_tri = 15
nb_f_cir = 10
nb_f_str = 7
nb_p_str = 15
nb_c_cir = 5
nb_c_str = 10
nb_f_spi = 3
var_p_str = 15
var_c_str = 15
width_spi = 0.3
width_str = 0.1

[data.tilings]
size_hex = 12.0
size_tri = 15.0
size_hex_and_tri = 13.0
size_squ_and_tri = 15.0
nb_del = 1000

[[entry]]
start = "2230"
end = "2300"
weight = 10
themes = ["rust"]
shapes = ["all"]

[[entry]]
start = "0800"
end = "1000"
weight = 10
themes = ["crimson"]
shapes = ["all"]
