[global]
deviation = 30
weight = 30
size = 15.0
width = 1366
height = 768

[colors]
black = "#000000"
navy = "#000080"
darkblue = "#00008B"
mediumblue = "#0000CD"
blue = "#0000FF"
darkgreen = "#006400"
green = "#008000"
teal = "#008080"
darkcyan = "#008B8B"
deepskyblue = "#00BFFF"
darkturquoise = "#00CED1"
mediumspringgreen = "#00FA9A"
lime = "#00FF00"
springgreen = "#00FF7F"
cyan = "#00FFFF"
aqua = "#00FFFF"
midnightblue = "#191970"
dodgerblue = "#1E90FF"
lightseagreen = "#20B2AA"
forestgreen = "#228B22"
seagreen = "#2E8B57"
darkslategray = "#2F4F4F"
darkslategrey = "#2F4F4F"
limegreen = "#32CD32"
mediumseagreen = "#3CB371"
turquoise = "#40E0D0"
royalblue = "#4169E1"
steelblue = "#4682B4"
darkslateblue = "#483D8B"
mediumturquoise = "#48D1CC"
indigo = "#4B0082"
darkolivegreen = "#556B2F"
cadetblue = "#5F9EA0"
cornflowerblue = "#6495ED"
mediumaquamarine = "#66CDAA"
dimgrey = "#696969"
dimgray = "#696969"
slateblue = "#6A5ACD"
olivedrab = "#6B8E23"
slategrey = "#708090"
slategray = "#708090"
lightslategray = "#778899"
lightslategrey = "#778899"
mediumslateblue = "#7B68EE"
lawngreen = "#7CFC00"
chartreuse = "#7FFF00"
aquamarine = "#7FFFD4"
maroon = "#800000"
purple = "#800080"
olive = "#808000"
gray = "#808080"
grey = "#808080"
skyblue = "#87CEEB"
lightskyblue = "#87CEFA"
blueviolet = "#8A2BE2"
darkred = "#8B0000"
darkmagenta = "#8B008B"
saddlebrown = "#8B4513"
darkseagreen = "#8FBC8F"
lightgreen = "#90EE90"
mediumpurple = "#9370DB"
darkviolet = "#9400D3"
palegreen = "#98FB98"
darkorchid = "#9932CC"
yellowgreen = "#9ACD32"
sienna = "#A0522D"
brown = "#A52A2A"
darkgray = "#A9A9A9"
darkgrey = "#A9A9A9"
lightblue = "#ADD8E6"
greenyellow = "#ADFF2F"
paleturquoise = "#AFEEEE"
lightsteelblue = "#B0C4DE"
powderblue = "#B0E0E6"
firebrick = "#B22222"
darkgoldenrod = "#B8860B"
mediumorchid = "#BA55D3"
rosybrown = "#BC8F8F"
darkkhaki = "#BDB76B"
silver = "#C0C0C0"
mediumvioletred = "#C71585"
indianred = "#CD5C5C"
peru = "#CD853F"
chocolate = "#D2691E"
tan = "#D2B48C"
lightgray = "#D3D3D3"
lightgrey = "#D3D3D3"
thistle = "#D8BFD8"
orchid = "#DA70D6"
goldenrod = "#DAA520"
palevioletred = "#DB7093"
crimson = "#DC143C"
gainsboro = "#DCDCDC"
plum = "#DDA0DD"
burlywood = "#DEB887"
lightcyan = "#E0FFFF"
lavender = "#E6E6FA"
darksalmon = "#E9967A"
violet = "#EE82EE"
palegoldenrod = "#EEE8AA"
lightcoral = "#F08080"
khaki = "#F0E68C"
aliceblue = "#F0F8FF"
honeydew = "#F0FFF0"
azure = "#F0FFFF"
sandybrown = "#F4A460"
wheat = "#F5DEB3"
beige = "#F5F5DC"
whitesmoke = "#F5F5F5"
mintcream = "#F5FFFA"
ghostwhite = "#F8F8FF"
salmon = "#FA8072"
antiquewhite = "#FAEBD7"
linen = "#FAF0E6"
lightgoldenrodyellow = "#FAFAD2"
oldlace = "#FDF5E6"
red = "#FF0000"
fuchsia = "#FF00FF"
magenta = "#FF00FF"
deeppink = "#FF1493"
orangered = "#FF4500"
tomato = "#FF6347"
hotpink = "#FF69B4"
coral = "#FF7F50"
darkorange = "#FF8C00"
lightsalmon = "#FFA07A"
orange = "#FFA500"
lightpink = "#FFB6C1"
pink = "#FFC0CB"
gold = "#FFD700"
peachpuff = "#FFDAB9"
navajowhite = "#FFDEAD"
moccasin = "#FFE4B5"
bisque = "#FFE4C4"
mistyrose = "#FFE4E1"
blanchedalmond = "#FFEBCD"
papayawhip = "#FFEFD5"
lavenderblush = "#FFF0F5"
seashell = "#FFF5EE"
cornsilk = "#FFF8DC"
lemonchiffon = "#FFFACD"
floralwhite = "#FFFAF0"
snow = "#FFFAFA"
yellow = "#FFFF00"
lightyellow = "#FFFFE0"
ivory = "#FFFFF0"
white = "#FFFFFF"

[themes]
rust = [["coral", 50], ["orange", 40], ["springgreen", 10]]
ocean = [["navy", 60], ["indigo", 30], ["mediumaquamarine", 30]]
sky = [["aqua", 50], ["gold", 30], ["skyblue", 50]]
night = [["midnightblue", 40], ["black", 30], ["slategray", 10]]
forest = [["palegreen", 30], ["forestgreen", 30], ["linen", 20]]
blood = [["maroon", 30], ["crimson", 10], ["salmon", 20]]
fire = [["yellow", 20], ["orangered", 30], ["darkred", 10], ["red", 20]]
spring = [["lawngreen", 30], ["gold", 10], ["aqua", 10], ["magenta", 10]]
shadow = [["indigo", 30], ["black", 10], ["purple", 20]]
dawn = [["goldenrod", 10], ["aqua", 30], ["magenta", 50]]
dusk = [["mediumslateblue", 30], ["hotpink", 20], ["darkorange", 20]]

[shapes]
all = []

[data.patterns]
nb_free_triangles = 15
nb_free_circles = 10
nb_free_stripes = 7
nb_parallel_stripes = 15
nb_concentric_circles = 13
nb_crossed_stripes = 10
nb_free_spirals = 3
nb_parallel_waves = 10
var_parallel_stripes = 15
var_crossed_stripes = 15
width_spiral = 0.3
width_stripe = 0.1
width_wave = 0.7

[data.tilings]
size_hex = 12.0
size_tri = 15.0
size_hex_and_tri = 13.0
size_squ_and_tri = 15.0
nb_delaunay = 3000

[[entry]]
themes = ["night"]
span = "0000-0559"
shapes = ["all"]

[[entry]]
themes = ["dawn"]
span = "0600-0729"
shapes = ["all"]

[[entry]]
themes = ["spring"]
span = "0730-0859"
shapes = ["all"]

[[entry]]
themes = ["sky"]
span = "0900-1029"
shapes = ["all"]

[[entry]]
themes = ["rust"]
span = "1030-1119"
shapes = ["all"]

[[entry]]
themes = ["fire"]
span = "1200-1329"
shapes = ["all"]

[[entry]]
themes = ["forest"]
span = "1330-1459"
shapes = ["all"]

[[entry]]
themes = ["ocean"]
span = "1500-1629"
shapes = ["all"]

[[entry]]
themes = ["blood"]
span = "1630-1759"
shapes = ["all"]

[[entry]]
themes = ["dusk"]
span = "1800-1929"
shapes = ["all"]

[[entry]]
themes = ["shadow"]
span = "1930-2059"
shapes = ["all"]

[[entry]]
themes = ["night"]
span = "2100-2359"
shapes = ["all"]
